services:

  spark:
    image: apache/spark:3.5.9
    container_name: streampulse-spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
    volumes:
      - ../streaming:/opt/spark/streaming

  spark-streaming:
    image: apache/spark:3.5.9
    container_name: streampulse-spark-streaming
    command: >
      /opt/spark/bin/spark-submit
      --conf spark.jars.ivy=/tmp/.ivy2
      --files /opt/spark/streaming/certs/secure-connect-streampulse.zip
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.9,com.datastax.spark:spark-cassandra-connector_2.12:3.5.1
      /opt/spark/streaming/spark_streaming.py
    environment:
      - HOME=/tmp
      - KAFKA_SERVER=${KAFKA_SERVER}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - ASTRA_TOKEN=${ASTRA_TOKEN}
    volumes:
      - ../streaming:/opt/spark/streaming
    networks:
      - default

  producer:
    build: ../producer
    container_name: streampulse-producer
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_CA_FILE: ca.pem
    restart: unless-stopped

  backend:
    build:
      context: ../backend
    container_name: streampulse-backend
    environment:
      ASTRA_TOKEN: ${ASTRA_TOKEN}
      ASTRA_SECURE_CONNECT_BUNDLE: /app/certs/secure-connect-streampulse.zip
    volumes:
      - ../streaming/certs:/app/certs
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    container_name: streampulse-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:5173"
    restart: unless-stopped
